SELECT tk.TEN_DANG_NHAP, tk.ID_VAI_TRO, vt.TEN_VAI_TRO, hv.HO_TEN
FROM TAI_KHOAN tk
LEFT JOIN VAI_TRO vt ON tk.ID_VAI_TRO = vt.ID_VAI_TRO
LEFT JOIN HOC_VIEN hv ON tk.ID_NGUOI_DUNG = hv.ID_HOC_VIEN
WHERE hv.HO_TEN LIKE '%LE VAN TRUONG%' OR tk.TEN_DANG_NHAP LIKE '%truong%';
