CREATE OR REPLACE PROCEDURE SP_GET_ACCOUNTANT_REG_BY_ID (
    p_id     IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT dk.ID_DANG_KY, dk.NGAY_DANG_KY, dk.TRANG_THAI,
               hv.ID_HOC_VIEN, hv.HO_TEN, tk.EMAIL, hv.SO_DIEN_THOAI,
               lh.ID_LOP_HOC, lh.TEN_LOP_HOC, kh.TEN_KHOA_HOC,
               NVL(kh.HOC_PHI_TIEU_CHUAN,0) AS HOC_PHI,
               hd.ID_HOA_DON
        FROM QLTT_ADMIN.DON_DANG_KY dk
        LEFT JOIN QLTT_ADMIN.HOC_VIEN hv ON hv.ID_HOC_VIEN = dk.ID_HOC_VIEN
        LEFT JOIN QLTT_ADMIN.TAI_KHOAN tk ON tk.ID_NGUOI_DUNG = hv.ID_HOC_VIEN
        LEFT JOIN QLTT_ADMIN.LOP_HOC lh ON lh.ID_LOP_HOC = dk.ID_LOP_HOC
        LEFT JOIN QLTT_ADMIN.KHOA_HOC kh ON kh.ID_KHOA_HOC = lh.ID_KHOA_HOC
        LEFT JOIN QLTT_ADMIN.HOA_DON hd ON hd.ID_DANG_KY = dk.ID_DANG_KY
        WHERE dk.ID_DANG_KY = p_id;
END;
/
