-- ====================================================================================
-- SCRIPT TỔNG HỢP: XÓA CSDL CŨ, TẠO CSDL TIẾNG VIỆT MỚI & BỔ SUNG PHÂN QUYỀN
-- Dành cho user: QLTT_ADMIN
-- ====================================================================================

-- ***** PHẦN 1: DỌN DẸP CÁC BẢNG TIẾNG ANH CŨ *****
-- Script này sẽ xóa các bảng cũ để chuẩn bị cho việc tạo mới.
BEGIN
   FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN 
             ('ATTENDANCE', 'PAYMENTS', 'INVOICES', 'REGISTRATIONS', 'SCHEDULES', 
              'CLASSES', 'COURSES', 'STUDENTS', 'ACCOUNTANTS', 'ACADEMIC_STAFF', 
              'TEACHERS', 'ACCOUNTS', 'ROLES', 'AUDIT_LOGS', '__EFMIGRATIONSHISTORY'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE "' || T.TABLE_NAME || '" CASCADE CONSTRAINTS';
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('Đã dọn dẹp xong các bảng tiếng Anh cũ.');
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Lỗi khi dọn dẹp hoặc không tìm thấy bảng cũ: ' || SQLERRM);
END;
/

-- ***** PHẦN 2: TẠO CẤU TRÚC BẢNG TIẾNG VIỆT MỚI *****

-- Bảng 1: VAI_TRO
CREATE TABLE VAI_TRO (
    ID_VAI_TRO     NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_VAI_TRO    NVARCHAR2(50)   NOT NULL UNIQUE
);
COMMENT ON TABLE VAI_TRO IS 'Lưu trữ các vai trò người dùng (HocVien, KeToan, NhanVienHocVu...)';

-- Bảng 2: TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    ID_NGUOI_DUNG   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_DANG_NHAP   VARCHAR2(50)    NOT NULL UNIQUE,
    MAT_KHAU        VARCHAR2(256)   NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL UNIQUE,
    ID_VAI_TRO      NUMBER(10)      NOT NULL,
    TRANG_THAI_KICH_HOAT NUMBER(1)  DEFAULT 1 NOT NULL,
    session_id_pc     varchar2(64),
    session_id_mobile varchar2(64),
    --SESSION_ID_HIENTAI VARCHAR2(255) ,
    CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (ID_VAI_TRO) REFERENCES VAI_TRO(ID_VAI_TRO)
);
COMMENT ON TABLE TAI_KHOAN IS 'Bảng cơ sở chứa thông tin đăng nhập chung của các tác nhân';

--ALTER TABLE TAI_KHOAN
--ADD (SESSION_ID_HIENTAI VARCHAR2(255) NULL);

--COMMENT ON COLUMN TAI_KHOAN.SESSION_ID_HIENTAI IS 'Lưu mã phiên làm việc (session ID) hợp lệ cuối cùng của người dùng.';
-- Bảng 3: HOC_VIEN
CREATE TABLE HOC_VIEN (
    ID_HOC_VIEN     NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_HOC_VIEN     VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    NGAY_SINH       DATE,
    SO_DIEN_THOAI   VARCHAR2(15),
    DIA_CHI         NVARCHAR2(255),
    CONSTRAINT FK_HOCVIEN_TAIKHOAN FOREIGN KEY (ID_HOC_VIEN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE HOC_VIEN IS 'Lưu thông tin chi tiết của học viên';

-- Bảng 4: NHAN_VIEN_HOC_VU
CREATE TABLE NHAN_VIEN_HOC_VU (
    ID_NHAN_VIEN    NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_NHAN_VIEN    VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15),
    CONSTRAINT FK_NVHOCVU_TAIKHOAN FOREIGN KEY (ID_NHAN_VIEN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE NHAN_VIEN_HOC_VU IS 'Lưu thông tin chi tiết của nhân viên học vụ';

-- Bảng 5: KE_TOAN
CREATE TABLE KE_TOAN (
    ID_KE_TOAN      NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_NHAN_VIEN    VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15),
    CONSTRAINT FK_KETOAN_TAIKHOAN FOREIGN KEY (ID_KE_TOAN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE KE_TOAN IS 'Lưu thông tin chi tiết của nhân viên kế toán';

-- Bảng 6: GIANG_VIEN
CREATE TABLE GIANG_VIEN (
    ID_GIANG_VIEN   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_GIANG_VIEN   VARCHAR2(20)    UNIQUE,
    CHUYEN_MON      NVARCHAR2(200),
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15)
);
COMMENT ON TABLE GIANG_VIEN IS 'Lưu thông tin của giảng viên (không có tài khoản đăng nhập)';

-- Bảng 7: KHOA_HOC
CREATE TABLE KHOA_HOC (
    ID_KHOA_HOC         NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_KHOA_HOC         VARCHAR2(20)    UNIQUE,
    TEN_KHOA_HOC        NVARCHAR2(200)  NOT NULL,
    MO_TA               CLOB,
    HOC_PHI_TIEU_CHUAN  NUMBER(12, 2)   DEFAULT 0 NOT NULL,
    NHAN_OLS            RAW(255)
);
COMMENT ON TABLE KHOA_HOC IS 'Quản lý các chương trình đào tạo gốc';

-- Bảng 8: LOP_HOC
CREATE TABLE LOP_HOC (
    ID_LOP_HOC          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_LOP_HOC          VARCHAR2(30)    UNIQUE,
    TEN_LOP_HOC         NVARCHAR2(200)  NOT NULL,
    NGAY_BAT_DAU        DATE            NOT NULL,
    NGAY_KET_THUC       DATE            NOT NULL,
    SI_SO_TOI_DA        NUMBER(3)       NOT NULL,
    TRANG_THAI          NVARCHAR2(30)   DEFAULT N'Đang tuyển sinh' 
                                        CHECK (TRANG_THAI IN (N'Đang tuyển sinh', N'Đã bắt đầu', N'Đã hủy', N'Đã kết thúc')),
    ID_KHOA_HOC         NUMBER(10)      NOT NULL,
    ID_GIANG_VIEN       NUMBER(10),
    CONSTRAINT FK_LOPHOC_KHOAHOC FOREIGN KEY (ID_KHOA_HOC) REFERENCES KHOA_HOC(ID_KHOA_HOC),
    CONSTRAINT FK_LOPHOC_GIANGVIEN FOREIGN KEY (ID_GIANG_VIEN) REFERENCES GIANG_VIEN(ID_GIANG_VIEN)
);
COMMENT ON TABLE LOP_HOC IS 'Quản lý các lớp học cụ thể được mở từ một khóa học';

-- Bảng 9: LICH_HOC
CREATE TABLE LICH_HOC (
    ID_LICH_HOC     NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_LOP_HOC      NUMBER(10)      NOT NULL,
    THU_TRONG_TUAN  NUMBER(1)       NOT NULL, -- 2=Thứ Hai, 3=Thứ Ba... 8=Chủ Nhật
    GIO_BAT_DAU     VARCHAR2(5)     NOT NULL, -- Định dạng HH24:MI
    GIO_KET_THUC    VARCHAR2(5)     NOT NULL, -- Định dạng HH24:MI
    CONSTRAINT FK_LICHHOC_LOPHOC FOREIGN KEY (ID_LOP_HOC) REFERENCES LOP_HOC(ID_LOP_HOC) ON DELETE CASCADE,
    CONSTRAINT CHK_THU_TRONG_TUAN CHECK (THU_TRONG_TUAN BETWEEN 2 AND 8)
);
COMMENT ON TABLE LICH_HOC IS 'Lưu lịch học cố định trong tuần của một lớp';

-- Bảng 10: DON_DANG_KY
CREATE TABLE DON_DANG_KY (
    ID_DANG_KY          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_DANG_KY          VARCHAR2(20)    NOT NULL UNIQUE,
    NGAY_DANG_KY        DATE            DEFAULT SYSDATE NOT NULL,
    NGAY_DUYET          DATE,
    TRANG_THAI          NVARCHAR2(30)   DEFAULT N'Chờ duyệt' 
                                        CHECK (TRANG_THAI IN (N'Chờ duyệt', N'Đã duyệt', N'Đã từ chối',N'Đã lập hóa đơn',N'Đã nhập học')),
    DIEM_CUOI_KHOA      NUMBER(5,2),
    ID_HOC_VIEN         NUMBER(10)      NOT NULL,
    ID_LOP_HOC          NUMBER(10)      NOT NULL,
    ID_NHAN_VIEN_DUYET  NUMBER(10),
    CONSTRAINT FK_DANGKY_HOCVIEN FOREIGN KEY (ID_HOC_VIEN) REFERENCES HOC_VIEN(ID_HOC_VIEN),
    CONSTRAINT FK_DANGKY_LOPHOC FOREIGN KEY (ID_LOP_HOC) REFERENCES LOP_HOC(ID_LOP_HOC),
    CONSTRAINT FK_DANGKY_NVHOCVU FOREIGN KEY (ID_NHAN_VIEN_DUYET) REFERENCES NHAN_VIEN_HOC_VU(ID_NHAN_VIEN),
    CONSTRAINT UK_HOCVIEN_LOPHOC UNIQUE (ID_HOC_VIEN, ID_LOP_HOC)
);
COMMENT ON TABLE DON_DANG_KY IS 'Ghi nhận việc một học viên đăng ký vào một lớp học';

-- Bảng 11: HOA_DON
CREATE TABLE HOA_DON (
    ID_HOA_DON          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_HOA_DON          VARCHAR2(50)    NOT NULL UNIQUE,
    NGAY_TAO            DATE            DEFAULT SYSDATE NOT NULL,
    NGAY_HET_HAN        DATE            NOT NULL,
    SO_TIEN             NUMBER(12, 2)   NOT NULL,
    TRANG_THAI          NVARCHAR2(30)   DEFAULT N'Chưa thanh toán' 
                                        CHECK (TRANG_THAI IN (N'Chưa thanh toán', N'Đã thanh toán')),
    ID_DANG_KY          NUMBER(10)      NOT NULL UNIQUE,
    CONSTRAINT FK_HOADON_DANGKY FOREIGN KEY (ID_DANG_KY) REFERENCES DON_DANG_KY(ID_DANG_KY)
);
COMMENT ON TABLE HOA_DON IS 'Lưu trữ thông tin hóa đơn học phí';

-- Bảng 12: PHIEU THANH_TOAN
CREATE TABLE PHIEU_THANH_TOAN (
    ID_THANH_TOAN           NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NGAY_THANH_TOAN         DATE            DEFAULT SYSDATE NOT NULL,
    SO_TIEN_DA_TRA          NUMBER(12, 2)   NOT NULL,
    PHUONG_THUC_THANH_TOAN  NVARCHAR2(50)   DEFAULT N'Chuyển khoản' 
                                            CHECK (PHUONG_THUC_THANH_TOAN IN (N'Tiền mặt', N'Chuyển khoản')),
    ID_HOA_DON             NUMBER(10)      NOT NULL UNIQUE,
    ID_KE_TOAN_XAC_NHAN     NUMBER(10),
    CONSTRAINT FK_THANHTOAN_HOADON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON(ID_HOA_DON),
    CONSTRAINT FK_THANHTOAN_KETOAN FOREIGN KEY (ID_KE_TOAN_XAC_NHAN) REFERENCES KE_TOAN(ID_KE_TOAN)
);
COMMENT ON TABLE PHIEU_THANH_TOAN IS 'Ghi nhận thanh toán cho một hóa đơn';

DROP TABLE THANH_TOAN
-- Bảng 13: NHAT_KY_HE_THONG
CREATE TABLE NHAT_KY_HE_THONG (
    ID_LOG              NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_BANG            VARCHAR2(30)    NOT NULL,
    ID_BAN_GHI          VARCHAR2(100)   NOT NULL,
    HANH_DONG           VARCHAR2(10)    NOT NULL,
    GIA_TRI_CU          NVARCHAR2(1000),
    GIA_TRI_MOI         NVARCHAR2(1000),
    THAY_DOI_BOI        VARCHAR2(50)    NOT NULL,
    THOI_GIAN_THAY_DOI  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE NHAT_KY_HE_THONG IS 'Lưu lại các dấu vết thay đổi dữ liệu quan trọng thông qua Trigger';

-- ***** PHẦN 3: TẠO BẢNG PHÂN QUYỀN - MỚI *****

-- Bảng 14: QUYEN (Định nghĩa các quyền hạn trong hệ thống)
CREATE TABLE QUYEN (
    ID_QUYEN      NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_QUYEN      VARCHAR2(20)    NOT NULL UNIQUE,
    TEN_QUYEN     NVARCHAR2(100)  NOT NULL UNIQUE,
    MO_TA         NVARCHAR2(255)
);
COMMENT ON TABLE QUYEN IS 'Lưu trữ danh sách các quyền hạn chức năng trong hệ thống';

-- Bảng 15: VAI_TRO_QUYEN (Bảng trung gian gán quyền cho vai trò)
CREATE TABLE VAI_TRO_QUYEN (
    ID_VAI_TRO    NUMBER(10)      NOT NULL,
    ID_QUYEN      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_VAITRO_QUYEN PRIMARY KEY (ID_VAI_TRO, ID_QUYEN),
    CONSTRAINT FK_VTQ_VAITRO FOREIGN KEY (ID_VAI_TRO) REFERENCES VAI_TRO(ID_VAI_TRO) ON DELETE CASCADE,
    CONSTRAINT FK_VTQ_QUYEN FOREIGN KEY (ID_QUYEN) REFERENCES QUYEN(ID_QUYEN) ON DELETE CASCADE
);
COMMENT ON TABLE VAI_TRO_QUYEN IS 'Gán các quyền hạn cụ thể cho từng vai trò';

-- ***** PHẦN 4: THÊM DỮ LIỆU MẪU BAN ĐẦU *****

-- Thêm dữ liệu cho VAI_TRO
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('HocVien');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('GiangVien');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('KeToan');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('NhanVienHocVu');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('QuanTriVienHeThong');

-- ***** THÊM DỮ LIỆU MẪU CHO BẢNG QUYEN *****

-- 1. Nhóm Quyền Quản Lý Tài Khoản & Phân Quyền
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_TAIKHOAN_XEM', N'Xem danh sách tài khoản', N'Cho phép xem danh sách và chi tiết các tài khoản người dùng trong hệ thống');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_TAIKHOAN_THEM', N'Thêm mới tài khoản', N'Cho phép tạo mới tài khoản cho người dùng');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_TAIKHOAN_SUA', N'Chỉnh sửa tài khoản', N'Cho phép chỉnh sửa thông tin của các tài khoản hiện có');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_TAIKHOAN_KHOA_MOKHOA', N'Khóa/Mở khóa tài khoản', N'Cho phép thay đổi trạng thái kích hoạt của tài khoản');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_PHANQUYEN', N'Quản lý phân quyền', N'Cho phép gán hoặc thu hồi các quyền hạn từ các vai trò');

-- 2. Nhóm Quyền Quản Lý Học Viên
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_HOCVIEN_XEM', N'Xem thông tin học viên', N'Cho phép xem hồ sơ chi tiết của học viên');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_HOCVIEN_SUA', N'Cập nhật thông tin học viên', N'Cho phép nhân viên hoặc chính học viên cập nhật hồ sơ của mình');

-- 3. Nhóm Quyền Quản Lý Đào Tạo
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_KHOAHOC_XEM', N'Xem danh sách khóa học', N'Cho phép xem thông tin về các khóa học của trung tâm');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_KHOAHOC_THEM', N'Thêm mới khóa học', N'Cho phép tạo ra một khóa học mới');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_KHOAHOC_SUA', N'Chỉnh sửa khóa học', N'Cho phép cập nhật thông tin của một khóa học');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_KHOAHOC_XOA', N'Xóa khóa học', N'Cho phép xóa một khóa học khỏi hệ thống');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_LOPHOC_XEM', N'Xem danh sách lớp học', N'Cho phép xem danh sách các lớp học đang và đã mở');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_LOPHOC_THEM', N'Thêm mới lớp học', N'Cho phép mở một lớp học mới từ một khóa học có sẵn');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_LOPHOC_SUA', N'Chỉnh sửa lớp học', N'Cho phép cập nhật thông tin chi tiết của lớp học');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_LOPHOC_XOA', N'Xóa lớp học', N'Cho phép xóa một lớp học');

-- 4. Nhóm Quyền Quản Lý Tuyển Sinh
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_DANGKY_XEM', N'Xem đơn đăng ký', N'Cho phép xem các đơn đăng ký của học viên vào các lớp');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_DANGKY_DUYET', N'Phê duyệt đơn đăng ký', N'Cho phép nhân viên học vụ phê duyệt hoặc từ chối một đơn đăng ký');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('HV_DANGKY_LOP', N'Học viên đăng ký lớp', N'Quyền cơ bản cho học viên để có thể tự đăng ký vào một lớp học');

-- 5. Nhóm Quyền Quản Lý Tài Chính
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_HOADON_XEM', N'Xem hóa đơn', N'Cho phép xem tất cả các hóa đơn đã được tạo');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_HOADON_LAP', N'Lập hóa đơn', N'Cho phép kế toán tạo hóa đơn học phí cho học viên');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('QL_THANHTOAN_XACNHAN', N'Xác nhận thanh toán', N'Cho phép kế toán ghi nhận và xác nhận khi học viên đã thanh toán học phí');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('HV_XEM_HOADON', N'Học viên xem hóa đơn cá nhân', N'Quyền cơ bản cho học viên để xem các hóa đơn của riêng mình');

-- 6. Nhóm Quyền Hệ Thống
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('HT_BACKUP_RESTORE', N'Sao lưu và Phục hồi dữ liệu', N'Cho phép quản trị viên thực hiện sao lưu và phục hồi cơ sở dữ liệu');
INSERT INTO QUYEN (MA_QUYEN, TEN_QUYEN, MO_TA) VALUES ('HT_XEM_NHATKY', N'Xem nhật ký hệ thống', N'Cho phép xem lại lịch sử các thay đổi dữ liệu quan trọng');

-- Thêm các khóa học TOEIC
INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('TOEIC550', N'TOEIC 550+', N'Khóa luyện thi TOEIC đạt 550 điểm trở lên.', 2500000);

INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('TOEIC650', N'TOEIC 650+', N'Khóa luyện thi TOEIC đạt 650 điểm trở lên.', 2800000);

-- Thêm các khóa học IELTS
INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('IELTS55', N'IELTS 5.5', N'Khóa học luyện thi IELTS đạt mục tiêu 5.5.', 3000000);

INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('IELTS65', N'IELTS 6.5', N'Khóa học luyện thi IELTS đạt mục tiêu 6.5.', 3500000);

INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('IELTS70', N'IELTS 7.0+', N'Khóa học luyện thi IELTS đạt mục tiêu từ 7.0 trở lên.', 4000000);

-- Thêm các khóa học giao tiếp
INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('GT_CB', N'Giao tiếp cơ bản', N'Khóa học tiếng Anh giao tiếp cơ bản, phù hợp cho người mới bắt đầu.', 1800000);

INSERT INTO KHOA_HOC (MA_KHOA_HOC, TEN_KHOA_HOC, MO_TA, HOC_PHI_TIEU_CHUAN)
VALUES ('GT_NC', N'Giao tiếp nâng cao', N'Khóa học tiếng Anh giao tiếp nâng cao, tập trung phát triển kỹ năng phản xạ và tự tin giao tiếp.', 2200000);

COMMIT;

-- Gán tất cả các quyền cho "QuanTriVienHeThong"
--INSERT INTO VAI_TRO_QUYEN (ID_VAI_TRO, ID_QUYEN)
--SELECT vt.ID_VAI_TRO, q.ID_QUYEN
--FROM VAI_TRO vt, QUYEN q
--WHERE vt.TEN_VAI_TRO = 'QuanTriVienHeThong';


COMMIT;

-- KẾT THÚC SCRIPT
DBMS_OUTPUT.PUT_LINE('Script đã thực thi thành công! Cơ sở dữ liệu tiếng Việt và hệ thống phân quyền đã được tạo.');
/