-- Bảng 1: VAI_TRO
create table vai_tro (
   id_vai_tro  number(10) generated by default on null as identity primary key,
   ten_vai_tro nvarchar2(50) not null unique
);
comment on table vai_tro is
   'Lưu trữ các vai trò người dùng (HocVien, KeToan, NhanVienHocVu...)';

-- Bảng 2: TAI_KHOAN
create table tai_khoan (
   id_nguoi_dung        number(10) generated by default on null as identity primary key,
   ten_dang_nhap        varchar2(50) not null unique,
   mat_khau             varchar2(256) not null,
   email                varchar2(100) not null unique,
   id_vai_tro           number(10) not null,
   trang_thai_kich_hoat number(1) default 1 not null,
   session_id_pc        varchar2(64),
   session_id_mobile    varchar2(64),
   constraint fk_taikhoan_vaitro foreign key ( id_vai_tro )
      references vai_tro ( id_vai_tro )
);
comment on table tai_khoan is
   'Bảng cơ sở chứa thông tin đăng nhập chung của các tác nhân';
-- Bảng 3: HOC_VIEN
create table hoc_vien (
   id_hoc_vien   number(10) primary key,
   ho_ten        nvarchar2(100) not null,
   ma_hoc_vien   varchar2(20) unique,
   gioi_tinh     nvarchar2(10) not null,
   ngay_sinh     date,
   so_dien_thoai varchar2(15),
   dia_chi       nvarchar2(255),
   constraint fk_hocvien_taikhoan foreign key ( id_hoc_vien )
      references tai_khoan ( id_nguoi_dung )
         on delete cascade
);
comment on table hoc_vien is
   'Lưu thông tin chi tiết của học viên';

-- Bảng 4: NHAN_VIEN_HOC_VU
create table nhan_vien_hoc_vu (
   id_nhan_vien  number(10) primary key,
   ho_ten        nvarchar2(100) not null,
   ma_nhan_vien  varchar2(20) unique,
   gioi_tinh     nvarchar2(10) not null,
   so_dien_thoai varchar2(15),
   constraint fk_nvhocvu_taikhoan foreign key ( id_nhan_vien )
      references tai_khoan ( id_nguoi_dung )
         on delete cascade
);
comment on table nhan_vien_hoc_vu is
   'Lưu thông tin chi tiết của nhân viên học vụ';

-- Bảng 5: KE_TOAN
create table ke_toan (
   id_ke_toan    number(10) primary key,
   ho_ten        nvarchar2(100) not null,
   ma_nhan_vien  varchar2(20) unique,
   gioi_tinh     nvarchar2(10) not null,
   so_dien_thoai varchar2(15),
   constraint fk_ketoan_taikhoan foreign key ( id_ke_toan )
      references tai_khoan ( id_nguoi_dung )
         on delete cascade
);
comment on table ke_toan is
   'Lưu thông tin chi tiết của nhân viên kế toán';

-- Bảng 6: GIANG_VIEN
create table giang_vien (
   id_giang_vien number(10) generated by default on null as identity primary key,
   ho_ten        nvarchar2(100) not null,
   ma_giang_vien varchar2(20) unique,
   chuyen_mon    nvarchar2(200),
   gioi_tinh     nvarchar2(10) not null,
   so_dien_thoai varchar2(15)
);
comment on table giang_vien is
   'Lưu thông tin của giảng viên (không có tài khoản đăng nhập)';

-- Bảng 7: KHOA_HOC
create table khoa_hoc (
   id_khoa_hoc        number(10) generated by default on null as identity primary key,
   ma_khoa_hoc        varchar2(20) unique,
   ten_khoa_hoc       nvarchar2(200) not null,
   mo_ta              clob,
   hoc_phi_tieu_chuan number(12,2) default 0 not null,
   nhan_ols           raw(255)
);
comment on table khoa_hoc is
   'Quản lý các chương trình đào tạo gốc';

-- Bảng 8: LOP_HOC
create table lop_hoc (
   id_lop_hoc    number(10) generated by default on null as identity primary key,
   ma_lop_hoc    varchar2(30) unique,
   ten_lop_hoc   nvarchar2(200) not null,
   ngay_bat_dau  date not null,
   ngay_ket_thuc date not null,
   si_so_toi_da  number(3) not null,
   trang_thai    nvarchar2(30) default N'Đang tuyển sinh' check ( trang_thai in ( N'Đang tuyển sinh',
                                                                               N'Đã bắt đầu',
                                                                               N'Đã hủy',
                                                                               N'Đã kết thúc' ) ),
   id_khoa_hoc   number(10) not null,
   id_giang_vien number(10),
   constraint fk_lophoc_khoahoc foreign key ( id_khoa_hoc )
      references khoa_hoc ( id_khoa_hoc ),
   constraint fk_lophoc_giangvien foreign key ( id_giang_vien )
      references giang_vien ( id_giang_vien )
);
comment on table lop_hoc is
   'Quản lý các lớp học cụ thể được mở từ một khóa học';

-- Bảng 9: LICH_HOC
create table lich_hoc (
   id_lich_hoc    number(10) generated by default on null as identity primary key,
   id_lop_hoc     number(10) not null,
   thu_trong_tuan number(1) not null, -- 2=Thứ Hai, 3=Thứ Ba... 8=Chủ Nhật
   gio_bat_dau    varchar2(5) not null, -- Định dạng HH24:MI
   gio_ket_thuc   varchar2(5) not null, -- Định dạng HH24:MI
   constraint fk_lichhoc_lophoc foreign key ( id_lop_hoc )
      references lop_hoc ( id_lop_hoc )
         on delete cascade,
   constraint chk_thu_trong_tuan check ( thu_trong_tuan between 2 and 8 )
);
comment on table lich_hoc is
   'Lưu lịch học cố định trong tuần của một lớp';

-- Bảng 10: DON_DANG_KY
create table don_dang_ky (
   id_dang_ky         number(10) generated by default on null as identity primary key,
   ma_dang_ky         varchar2(20) not null unique,
   ngay_dang_ky       date default sysdate not null,
   ngay_duyet         date,
   trang_thai         nvarchar2(30) default N'Chờ duyệt' check ( trang_thai in ( N'Chờ duyệt',
                                                                         N'Đã duyệt',
                                                                         N'Đã từ chối',
                                                                         N'Đã lập hóa đơn',
                                                                         N'Đã nhập học' ) ),
   diem_cuoi_khoa     number(5,2),
   id_hoc_vien        number(10) not null,
   id_lop_hoc         number(10) not null,
   id_nhan_vien_duyet number(10),
   constraint fk_dangky_hocvien foreign key ( id_hoc_vien )
      references hoc_vien ( id_hoc_vien ),
   constraint fk_dangky_lophoc foreign key ( id_lop_hoc )
      references lop_hoc ( id_lop_hoc ),
   constraint fk_dangky_nvhocvu foreign key ( id_nhan_vien_duyet )
      references nhan_vien_hoc_vu ( id_nhan_vien ),
   constraint uk_hocvien_lophoc unique ( id_hoc_vien,
                                         id_lop_hoc )
);
comment on table don_dang_ky is
   'Ghi nhận việc một học viên đăng ký vào một lớp học';

-- Bảng 11: HOA_DON
create table hoa_don (
   id_hoa_don   number(10) generated by default on null as identity primary key,
   ma_hoa_don   varchar2(50) not null unique,
   ngay_tao     date default sysdate not null,
   ngay_het_han date not null,
   so_tien      number(12,2) not null,
   trang_thai   nvarchar2(30) default N'Chưa thanh toán' check ( trang_thai in ( N'Chưa thanh toán',
                                                                               N'Đã thanh toán' ) ),
   id_dang_ky   number(10) not null unique,
   constraint fk_hoadon_dangky foreign key ( id_dang_ky )
      references don_dang_ky ( id_dang_ky )
);
comment on table hoa_don is
   'Lưu trữ thông tin hóa đơn học phí';

-- Bảng 12: PHIEU THANH_TOAN
create table phieu_thanh_toan (
   id_thanh_toan          number(10) generated by default on null as identity primary key,
   ngay_thanh_toan        date default sysdate not null,
   so_tien_da_tra         number(12,2) not null,
   phuong_thuc_thanh_toan nvarchar2(50) default N'Chuyển khoản' check ( phuong_thuc_thanh_toan in ( N'Tiền mặt',
                                                                                                    N'Chuyển khoản' ) ),
   id_hoa_don             number(10) not null unique,
   id_ke_toan_xac_nhan    number(10),
   constraint fk_thanhtoan_hoadon foreign key ( id_hoa_don )
      references hoa_don ( id_hoa_don ),
   constraint fk_thanhtoan_ketoan foreign key ( id_ke_toan_xac_nhan )
      references ke_toan ( id_ke_toan )
);
comment on table phieu_thanh_toan is
   'Ghi nhận thanh toán cho một hóa đơn';