-- ====================================================================================
-- SCRIPT TỔNG HỢP: XÓA CSDL CŨ, TẠO CSDL TIẾNG VIỆT MỚI & BỔ SUNG PHÂN QUYỀN
-- Dành cho user: QLTT_ADMIN
-- ====================================================================================

-- ***** PHẦN 1: DỌN DẸP CÁC BẢNG TIẾNG ANH CŨ *****
-- Script này sẽ xóa các bảng cũ để chuẩn bị cho việc tạo mới.
BEGIN
   FOR T IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN 
             ('ATTENDANCE', 'PAYMENTS', 'INVOICES', 'REGISTRATIONS', 'SCHEDULES', 
              'CLASSES', 'COURSES', 'STUDENTS', 'ACCOUNTANTS', 'ACADEMIC_STAFF', 
              'TEACHERS', 'ACCOUNTS', 'ROLES', 'AUDIT_LOGS', '__EFMIGRATIONSHISTORY'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE "' || T.TABLE_NAME || '" CASCADE CONSTRAINTS';
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('Đã dọn dẹp xong các bảng tiếng Anh cũ.');
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Lỗi khi dọn dẹp hoặc không tìm thấy bảng cũ: ' || SQLERRM);
END;
/

-- ***** PHẦN 2: TẠO CẤU TRÚC BẢNG TIẾNG VIỆT MỚI *****

-- Bảng 1: VAI_TRO
CREATE TABLE VAI_TRO (
    ID_VAI_TRO     NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_VAI_TRO    NVARCHAR2(50)   NOT NULL UNIQUE
);
COMMENT ON TABLE VAI_TRO IS 'Lưu trữ các vai trò người dùng (HocVien, KeToan, NhanVienHocVu...)';

-- Bảng 2: TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    ID_NGUOI_DUNG   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_DANG_NHAP   VARCHAR2(50)    NOT NULL UNIQUE,
    MAT_KHAU        VARCHAR2(256)   NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL UNIQUE,
    ID_VAI_TRO      NUMBER(10)      NOT NULL,
    TRANG_THAI_KICH_HOAT NUMBER(1)  DEFAULT 1 NOT NULL,
    CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (ID_VAI_TRO) REFERENCES VAI_TRO(ID_VAI_TRO)
);
COMMENT ON TABLE TAI_KHOAN IS 'Bảng cơ sở chứa thông tin đăng nhập chung của các tác nhân';

-- Bảng 3: HOC_VIEN
CREATE TABLE HOC_VIEN (
    ID_HOC_VIEN     NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_HOC_VIEN     VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    NGAY_SINH       DATE,
    SO_DIEN_THOAI   VARCHAR2(15),
    DIA_CHI         NVARCHAR2(255),
    CONSTRAINT FK_HOCVIEN_TAIKHOAN FOREIGN KEY (ID_HOC_VIEN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE HOC_VIEN IS 'Lưu thông tin chi tiết của học viên';

-- Bảng 4: NHAN_VIEN_HOC_VU
CREATE TABLE NHAN_VIEN_HOC_VU (
    ID_NHAN_VIEN    NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_NHAN_VIEN    VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15),
    CONSTRAINT FK_NVHOCVU_TAIKHOAN FOREIGN KEY (ID_NHAN_VIEN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE NHAN_VIEN_HOC_VU IS 'Lưu thông tin chi tiết của nhân viên học vụ';

-- Bảng 5: KE_TOAN
CREATE TABLE KE_TOAN (
    ID_KE_TOAN      NUMBER(10)      PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_NHAN_VIEN    VARCHAR2(20)    UNIQUE,
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15),
    CONSTRAINT FK_KETOAN_TAIKHOAN FOREIGN KEY (ID_KE_TOAN) REFERENCES TAI_KHOAN(ID_NGUOI_DUNG) ON DELETE CASCADE
);
COMMENT ON TABLE KE_TOAN IS 'Lưu thông tin chi tiết của nhân viên kế toán';

-- Bảng 6: GIANG_VIEN
CREATE TABLE GIANG_VIEN (
    ID_GIANG_VIEN   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    HO_TEN          NVARCHAR2(100)  NOT NULL,
    MA_GIANG_VIEN   VARCHAR2(20)    UNIQUE,
    CHUYEN_MON      NVARCHAR2(200),
    GIOI_TINH       NVARCHAR2(10)   NOT NULL,
    SO_DIEN_THOAI   VARCHAR2(15)
);
COMMENT ON TABLE GIANG_VIEN IS 'Lưu thông tin của giảng viên (không có tài khoản đăng nhập)';

-- Bảng 7: KHOA_HOC
CREATE TABLE KHOA_HOC (
    ID_KHOA_HOC         NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_KHOA_HOC         VARCHAR2(20)    UNIQUE,
    TEN_KHOA_HOC        NVARCHAR2(200)  NOT NULL,
    MO_TA               CLOB,
    HOC_PHI_TIEU_CHUAN  NUMBER(12, 2)   DEFAULT 0 NOT NULL,
    NHAN_OLS            RAW(255)
);
COMMENT ON TABLE KHOA_HOC IS 'Quản lý các chương trình đào tạo gốc';

-- Bảng 8: LOP_HOC
CREATE TABLE LOP_HOC (
    ID_LOP_HOC          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_LOP_HOC          VARCHAR2(30)    UNIQUE,
    TEN_LOP_HOC         NVARCHAR2(200)  NOT NULL,
    NGAY_BAT_DAU        DATE            NOT NULL,
    NGAY_KET_THUC       DATE            NOT NULL,
    SI_SO_TOI_DA        NUMBER(3)       NOT NULL,
    TRANG_THAI          NVARCHAR2(30)   NOT NULL,
    ID_KHOA_HOC         NUMBER(10)      NOT NULL,
    ID_GIANG_VIEN       NUMBER(10),
    CONSTRAINT FK_LOPHOC_KHOAHOC FOREIGN KEY (ID_KHOA_HOC) REFERENCES KHOA_HOC(ID_KHOA_HOC),
    CONSTRAINT FK_LOPHOC_GIANGVIEN FOREIGN KEY (ID_GIANG_VIEN) REFERENCES GIANG_VIEN(ID_GIANG_VIEN)
);
COMMENT ON TABLE LOP_HOC IS 'Quản lý các lớp học cụ thể được mở từ một khóa học';

-- Bảng 9: LICH_HOC
CREATE TABLE LICH_HOC (
    ID_LICH_HOC     NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_LOP_HOC      NUMBER(10)      NOT NULL,
    THU_TRONG_TUAN  NUMBER(1)       NOT NULL, -- 2=Thứ Hai, 3=Thứ Ba... 8=Chủ Nhật
    GIO_BAT_DAU     VARCHAR2(5)     NOT NULL, -- Định dạng HH24:MI
    GIO_KET_THUC    VARCHAR2(5)     NOT NULL, -- Định dạng HH24:MI
    CONSTRAINT FK_LICHHOC_LOPHOC FOREIGN KEY (ID_LOP_HOC) REFERENCES LOP_HOC(ID_LOP_HOC) ON DELETE CASCADE,
    CONSTRAINT CHK_THU_TRONG_TUAN CHECK (THU_TRONG_TUAN BETWEEN 2 AND 8)
);
COMMENT ON TABLE LICH_HOC IS 'Lưu lịch học cố định trong tuần của một lớp';

-- Bảng 10: DON_DANG_KY
CREATE TABLE DON_DANG_KY (
    ID_DANG_KY          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_DANG_KY          VARCHAR2(20)    NOT NULL UNIQUE,
    NGAY_DANG_KY        DATE            DEFAULT SYSDATE NOT NULL,
    NGAY_DUYET          DATE,
    TRANG_THAI          NVARCHAR2(30)   NOT NULL,
    DIEM_CUOI_KHOA      NUMBER(5,2),
    ID_HOC_VIEN         NUMBER(10)      NOT NULL,
    ID_LOP_HOC          NUMBER(10)      NOT NULL,
    ID_NHAN_VIEN_DUYET  NUMBER(10),
    CONSTRAINT FK_DANGKY_HOCVIEN FOREIGN KEY (ID_HOC_VIEN) REFERENCES HOC_VIEN(ID_HOC_VIEN),
    CONSTRAINT FK_DANGKY_LOPHOC FOREIGN KEY (ID_LOP_HOC) REFERENCES LOP_HOC(ID_LOP_HOC),
    CONSTRAINT FK_DANGKY_NVHOCVU FOREIGN KEY (ID_NHAN_VIEN_DUYET) REFERENCES NHAN_VIEN_HOC_VU(ID_NHAN_VIEN),
    CONSTRAINT UK_HOCVIEN_LOPHOC UNIQUE (ID_HOC_VIEN, ID_LOP_HOC)
);
COMMENT ON TABLE DON_DANG_KY IS 'Ghi nhận việc một học viên đăng ký vào một lớp học';

-- Bảng 11: HOA_DON
CREATE TABLE HOA_DON (
    ID_HOA_DON          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_HOA_DON          VARCHAR2(50)    NOT NULL UNIQUE,
    NGAY_TAO            DATE            DEFAULT SYSDATE NOT NULL,
    NGAY_HET_HAN        DATE            NOT NULL,
    SO_TIEN             NUMBER(12, 2)   NOT NULL,
    TRANG_THAI          NVARCHAR2(30)   NOT NULL,
    ID_DANG_KY          NUMBER(10)      NOT NULL UNIQUE,
    CONSTRAINT FK_HOADON_DANGKY FOREIGN KEY (ID_DANG_KY) REFERENCES DON_DANG_KY(ID_DANG_KY)
);
COMMENT ON TABLE HOA_DON IS 'Lưu trữ thông tin hóa đơn học phí';

-- Bảng 12: THANH_TOAN
CREATE TABLE THANH_TOAN (
    ID_THANH_TOAN           NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NGAY_THANH_TOAN         DATE            DEFAULT SYSDATE NOT NULL,
    SO_TIEN_DA_TRA          NUMBER(12, 2)   NOT NULL,
    PHUONG_THUC_THANH_TOAN  NVARCHAR2(50),
    ID_HOA_DON             NUMBER(10)      NOT NULL UNIQUE,
    ID_KE_TOAN_XAC_NHAN     NUMBER(10),
    CONSTRAINT FK_THANHTOAN_HOADON FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON(ID_HOA_DON),
    CONSTRAINT FK_THANHTOAN_KETOAN FOREIGN KEY (ID_KE_TOAN_XAC_NHAN) REFERENCES KE_TOAN(ID_KE_TOAN)
);
COMMENT ON TABLE THANH_TOAN IS 'Ghi nhận thanh toán cho một hóa đơn';

-- Bảng 13: NHAT_KY_HE_THONG
CREATE TABLE NHAT_KY_HE_THONG (
    ID_LOG              NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TEN_BANG            VARCHAR2(30)    NOT NULL,
    ID_BAN_GHI          VARCHAR2(100)   NOT NULL,
    HANH_DONG           VARCHAR2(10)    NOT NULL,
    GIA_TRI_CU          NVARCHAR2(1000),
    GIA_TRI_MOI         NVARCHAR2(1000),
    THAY_DOI_BOI        VARCHAR2(50)    NOT NULL,
    THOI_GIAN_THAY_DOI  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE NHAT_KY_HE_THONG IS 'Lưu lại các dấu vết thay đổi dữ liệu quan trọng thông qua Trigger';

-- ***** PHẦN 3: TẠO BẢNG PHÂN QUYỀN - MỚI *****

-- Bảng 14: QUYEN (Định nghĩa các quyền hạn trong hệ thống)
CREATE TABLE QUYEN (
    ID_QUYEN      NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_QUYEN        VARCHAR2(20)    NOT NULL UNIQUE,
    TEN_QUYEN     NVARCHAR2(100)  NOT NULL UNIQUE,
    MO_TA         NVARCHAR2(255)
);
COMMENT ON TABLE QUYEN IS 'Lưu trữ danh sách các quyền hạn chức năng trong hệ thống';

-- Bảng 15: VAI_TRO_QUYEN (Bảng trung gian gán quyền cho vai trò)
CREATE TABLE VAI_TRO_QUYEN (
    ID_VAI_TRO    NUMBER(10)      NOT NULL,
    ID_QUYEN      NUMBER(10)      NOT NULL,
    CONSTRAINT PK_VAITRO_QUYEN PRIMARY KEY (ID_VAI_TRO, ID_QUYEN),
    CONSTRAINT FK_VTQ_VAITRO FOREIGN KEY (ID_VAI_TRO) REFERENCES VAI_TRO(ID_VAI_TRO) ON DELETE CASCADE,
    CONSTRAINT FK_VTQ_QUYEN FOREIGN KEY (ID_QUYEN) REFERENCES QUYEN(ID_QUYEN) ON DELETE CASCADE
);
COMMENT ON TABLE VAI_TRO_QUYEN IS 'Gán các quyền hạn cụ thể cho từng vai trò';

-- ***** PHẦN 4: THÊM DỮ LIỆU MẪU BAN ĐẦU *****

-- Thêm dữ liệu cho VAI_TRO
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('HocVien');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('GiangVien');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('KeToan');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('NhanVienHocVu');
INSERT INTO VAI_TRO (TEN_VAI_TRO) VALUES ('QuanTriVienHeThong');

-- Thêm dữ liệu cho QUYEN
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Xem danh sách khóa học', 'Cho phép xem danh sách tất cả các khóa học');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Tạo và cập nhật khóa học', 'Cho phép thêm mới hoặc chỉnh sửa thông tin khóa học');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Xem danh sách lớp học', 'Cho phép xem danh sách các lớp học đang và sắp mở');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Tạo và cập nhật lớp học', 'Cho phép mở lớp học mới hoặc chỉnh sửa thông tin lớp');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Phê duyệt đơn đăng ký', 'Cho phép nhân viên học vụ duyệt hoặc từ chối đơn đăng ký của học viên');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Lập hóa đơn học phí', 'Cho phép kế toán tạo hóa đơn cho các đơn đăng ký đã được duyệt');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Xác nhận thanh toán', 'Cho phép kế toán xác nhận khi học viên đã thanh toán hóa đơn');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Xem báo cáo tài chính', 'Cho phép xem các báo cáo liên quan đến doanh thu, công nợ');
INSERT INTO QUYEN (TEN_QUYEN, MO_TA) VALUES ('Quản lý người dùng', 'Cho phép quản trị viên tạo, xóa, sửa tài khoản người dùng');


-- Gán quyền mẫu cho vai trò "NhanVienHocVu"
INSERT INTO VAI_TRO_QUYEN (ID_VAI_TRO, ID_QUYEN)
SELECT vt.ID_VAI_TRO, q.ID_QUYEN
FROM VAI_TRO vt, QUYEN q
WHERE vt.TEN_VAI_TRO = 'NhanVienHocVu'
  AND q.TEN_QUYEN IN ('Xem danh sách khóa học', 'Tạo và cập nhật khóa học', 'Xem danh sách lớp học', 'Tạo và cập nhật lớp học', 'Phê duyệt đơn đăng ký');

-- Gán quyền mẫu cho vai trò "KeToan"
INSERT INTO VAI_TRO_QUYEN (ID_VAI_TRO, ID_QUYEN)
SELECT vt.ID_VAI_TRO, q.ID_QUYEN
FROM VAI_TRO vt, QUYEN q
WHERE vt.TEN_VAI_TRO = 'KeToan'
  AND q.TEN_QUYEN IN ('Lập hóa đơn học phí', 'Xác nhận thanh toán', 'Xem báo cáo tài chính', 'Xem danh sách khóa học', 'Xem danh sách lớp học');

-- Gán tất cả các quyền cho "QuanTriVienHeThong"
INSERT INTO VAI_TRO_QUYEN (ID_VAI_TRO, ID_QUYEN)
SELECT vt.ID_VAI_TRO, q.ID_QUYEN
FROM VAI_TRO vt, QUYEN q
WHERE vt.TEN_VAI_TRO = 'QuanTriVienHeThong';


--COMMIT;

-- KẾT THÚC SCRIPT
DBMS_OUTPUT.PUT_LINE('Script đã thực thi thành công! Cơ sở dữ liệu tiếng Việt và hệ thống phân quyền đã được tạo.');
/
-- ============================================================================
-- Triển khai View/Procedure/Grant cho luồng hoạt động theo schema tiếng Việt
-- Yêu cầu: kết nối bằng user QLTT_ADMIN (hoặc schema chủ sở hữu các bảng)
-- ============================================================================
   SET SERVEROUTPUT ON;

-- View hồ sơ học viên theo USER
create or replace view v_thongtin_canhan_hv as
   select hv.ho_ten,
          hv.ma_hoc_vien,
          hv.gioi_tinh,
          hv.ngay_sinh,
          hv.so_dien_thoai,
          hv.dia_chi,
          tk.email,
          tk.ten_dang_nhap
     from hoc_vien hv
     join tai_khoan tk
   on tk.id_nguoi_dung = hv.id_hoc_vien
    where upper(tk.ten_dang_nhap) = user;

-- Quyền cập nhật số điện thoại và địa chỉ trên view hồ sơ
-- Lưu ý: cần INSTEAD OF trigger nếu Oracle không cho UPDATE trực tiếp view này
-- Ở đây giả sử hai cột map thẳng xuống HOC_VIEN, dùng trigger để chuyển UPDATE vào bảng gốc
create or replace trigger trg_v_tt_canhan_update instead of
   update of so_dien_thoai,dia_chi on v_thongtin_canhan_hv
   for each row
begin
   update hoc_vien hv
      set hv.so_dien_thoai = :new.so_dien_thoai,
          hv.dia_chi = :new.dia_chi
    where hv.id_hoc_vien = (
      select tk.id_nguoi_dung
        from tai_khoan tk
       where upper(tk.ten_dang_nhap) = user
   );
end;
/

grant select on v_thongtin_canhan_hv to public;
grant update ( so_dien_thoai,
               dia_chi ) on v_thongtin_canhan_hv to public;

-- View danh sách khóa học công khai
create or replace view v_danhsach_khoahoc as
  select ma_khoa_hoc,
         ten_khoa_hoc,
         mo_ta,
         hoc_phi_tieu_chuan
    from khoa_hoc;
/

grant select on v_danhsach_khoahoc to public;

-- Thủ tục học viên gửi yêu cầu đăng ký khóa học
create or replace procedure sp_gui_yeu_cau_dang_ky_khoa (
   p_course_code in varchar2,
   p_ket_qua     out nvarchar2
) as
   v_user_id     number;
   v_hoc_vien_id number;
   v_khoa_id     number;
begin
   if p_course_code is null then
      p_ket_qua := N'Mã khóa học không hợp lệ';
      return;
   end if;
   select id_nguoi_dung
     into v_user_id
     from tai_khoan
    where upper(ten_dang_nhap) = user;
   select id_hoc_vien
     into v_hoc_vien_id
     from hoc_vien
    where id_hoc_vien = v_user_id;
   select id_khoa_hoc
     into v_khoa_id
     from khoa_hoc
    where ma_khoa_hoc = p_course_code;

    -- Tạo bản ghi đơn đăng ký ở trạng thái Chờ duyệt, gán lớp đang tuyển sinh (nếu có)
    -- Tùy bạn có muốn tạo bảng YEU_CAU_DANG_KY hay tạo trực tiếp DON_DANG_KY với lớp đang mở.
   insert into don_dang_ky (
      ma_dang_ky,
      ngay_dang_ky,
      trang_thai,
      id_hoc_vien,
      id_lop_hoc
   ) values ( 'DGK_'
              || to_char(
      sysdate,
      'YYYYMMDDHH24MISS'
   )
              || '_'
              || dbms_random.value(
      1000,
      9999
   ),
              sysdate,
              N'Chờ duyệt',
              v_hoc_vien_id,
              (
                 select id_lop_hoc
                   from lop_hoc
                                    where id_khoa_hoc = v_khoa_id
                                        and trang_thai = N'Đang tuyển sinh'
                  fetch first 1 rows only
              ) );

   p_ket_qua := N'Gửi yêu cầu thành công';
exception
   when no_data_found then
      p_ket_qua := N'Không tìm thấy học viên/lớp/khóa học phù hợp';
   when others then
      p_ket_qua := N'Lỗi: ' || sqlerrm;
end;
/

-- Cấp quyền cho vai trò
-- Học viên: xem/ cập nhật hồ sơ; execute thủ tục gửi yêu cầu
grant select on v_thongtin_canhan_hv to role_hocvien;
grant update ( so_dien_thoai,
               dia_chi ) on v_thongtin_canhan_hv to role_hocvien;
grant execute on sp_gui_yeu_cau_dang_ky_khoa to role_hocvien;

-- Nhân viên học vụ: CRUD khóa/lớp/lịch
grant select,insert,update,delete on khoa_hoc to role_nhanvienhocvu;
grant select,insert,update,delete on lop_hoc to role_nhanvienhocvu;
grant select,insert,update,delete on lich_hoc to role_nhanvienhocvu;
grant select,update on don_dang_ky to role_nhanvienhocvu;

-- Cho phép học viên tự tạo đơn đăng ký lớp (qua API per-user)
grant insert on don_dang_ky to role_hocvien;

-- Có thể gán quyền cho PUBLIC nếu môi trường phát triển đơn giản
-- GRANT EXECUTE ON SP_GUI_YEU_CAU_DANG_KY_KHOA TO PUBLIC;

begin
   dbms_output.put_line('Triển khai view/proc/grant hoàn tất.');
end;
/

-- View trả về ID_NGUOI_DUNG của phiên hiện tại
create or replace view v_current_user_id as
select tk.id_nguoi_dung as id_nguoi_dung
  from tai_khoan tk
 where upper(tk.ten_dang_nhap) = user;
/
grant select on v_current_user_id to role_hocvien;

-- View các đơn đăng ký của chính học viên (lọc theo USER)
create or replace view v_dang_ky_cua_toi as
select dk.id_dang_ky,
       dk.ma_dang_ky,
       dk.ngay_dang_ky,
       dk.trang_thai,
       kh.ten_khoa_hoc,
       lh.ten_lop_hoc,
       lh.ngay_bat_dau,
       lh.ngay_ket_thuc,
       dk.id_hoc_vien,
       dk.id_lop_hoc
  from don_dang_ky dk
  join lop_hoc lh on dk.id_lop_hoc = lh.id_lop_hoc
  join khoa_hoc kh on lh.id_khoa_hoc = kh.id_khoa_hoc
 where dk.id_hoc_vien = (select id_nguoi_dung from v_current_user_id);
/
grant select on v_dang_ky_cua_toi to role_hocvien;

-- View hóa đơn của các đơn đăng ký thuộc học viên hiện tại
create or replace view v_hoa_don_cua_toi as
select hd.id_hoa_don,
       hd.ma_hoa_don,
       hd.ngay_tao,
       hd.ngay_het_han,
       hd.so_tien,
       hd.trang_thai,
       hd.id_dang_ky
  from hoa_don hd
  join don_dang_ky dk on dk.id_dang_ky = hd.id_dang_ky
 where dk.id_hoc_vien = (select id_nguoi_dung from v_current_user_id);
/
grant select on v_hoa_don_cua_toi to role_hocvien;

begin
   dbms_output.put_line('Bo sung view v_current_user_id, v_dang_ky_cua_toi, v_hoa_don_cua_toi va grant quyen xong.');
end;
/