-- Fix missing roles in TAI_KHOAN table based on user existence in specific tables

-- 1. Fix Student Roles (ID_VAI_TRO = 1)
UPDATE QLTT_ADMIN.TAI_KHOAN tk
SET tk.ID_VAI_TRO = 1
WHERE (tk.ID_VAI_TRO IS NULL OR tk.ID_VAI_TRO = 0)
AND EXISTS (SELECT 1 FROM QLTT_ADMIN.HOC_VIEN hv WHERE hv.ID_HOC_VIEN = tk.ID_NGUOI_DUNG);

-- 2. Fix Teacher Roles (ID_VAI_TRO = 2)
UPDATE QLTT_ADMIN.TAI_KHOAN tk
SET tk.ID_VAI_TRO = 2
WHERE (tk.ID_VAI_TRO IS NULL OR tk.ID_VAI_TRO = 0)
AND EXISTS (SELECT 1 FROM QLTT_ADMIN.GIANG_VIEN gv WHERE gv.ID_GIANG_VIEN = tk.ID_NGUOI_DUNG);

-- 3. Fix Accountant Roles (ID_VAI_TRO = 3)
UPDATE QLTT_ADMIN.TAI_KHOAN tk
SET tk.ID_VAI_TRO = 3
WHERE (tk.ID_VAI_TRO IS NULL OR tk.ID_VAI_TRO = 0)
AND EXISTS (SELECT 1 FROM QLTT_ADMIN.KE_TOAN kt WHERE kt.ID_KE_TOAN = tk.ID_NGUOI_DUNG);

-- 4. Fix Academic Staff Roles (ID_VAI_TRO = 4)
UPDATE QLTT_ADMIN.TAI_KHOAN tk
SET tk.ID_VAI_TRO = 4
WHERE (tk.ID_VAI_TRO IS NULL OR tk.ID_VAI_TRO = 0)
AND EXISTS (SELECT 1 FROM QLTT_ADMIN.NHAN_VIEN_HOC_VU nv WHERE nv.ID_NHAN_VIEN = tk.ID_NGUOI_DUNG);

COMMIT;

-- Verify updates
SELECT tk.TEN_DANG_NHAP, tk.ID_VAI_TRO, vt.TEN_VAI_TRO
FROM QLTT_ADMIN.TAI_KHOAN tk
LEFT JOIN QLTT_ADMIN.VAI_TRO vt ON vt.ID_VAI_TRO = tk.ID_VAI_TRO
WHERE tk.TEN_DANG_NHAP LIKE '%TRUONG%' OR tk.TEN_DANG_NHAP LIKE '%NV%';
