-- Grant Course Management Permissions

-- Grant to ROLE_NHANVIEN (Academic Staff)
GRANT EXECUTE ON SP_CREATE_COURSE TO ROLE_NHANVIEN;
GRANT EXECUTE ON SP_UPDATE_COURSE TO ROLE_NHANVIEN;
GRANT EXECUTE ON SP_DELETE_COURSE TO ROLE_NHANVIEN;

-- Grant to ROLE_GIANGVIEN (Teachers - if they are allowed to manage courses)
GRANT EXECUTE ON SP_CREATE_COURSE TO ROLE_GIANGVIEN;
GRANT EXECUTE ON SP_UPDATE_COURSE TO ROLE_GIANGVIEN;
GRANT EXECUTE ON SP_DELETE_COURSE TO ROLE_GIANGVIEN;

-- Grant to ROLE_KETOAN (Accountant - View only usually, but granting just in case)
-- GRANT EXECUTE ON SP_DELETE_COURSE TO ROLE_KETOAN;

COMMIT;
