-- Grant permissions for Accountant (ROLE_KETOAN) to create and manage invoices
GRANT EXECUTE ON SP_GET_REGISTRATION_BY_ID TO ROLE_KETOAN;
GRANT EXECUTE ON SP_CREATE_INVOICE TO ROLE_KETOAN;
GRANT EXECUTE ON SP_UPDATE_INVOICE_STATUS TO ROLE_KETOAN;
GRANT EXECUTE ON SP_MARK_INVOICE_PRINTED TO ROLE_KETOAN;

-- Grant permissions for viewing courses (needed for Profile and other lists)
-- Grant to all roles who might need to see course lists
GRANT EXECUTE ON SP_GET_ALL_COURSES TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_ALL_COURSES TO ROLE_GIANGVIEN;
GRANT EXECUTE ON SP_GET_ALL_COURSES TO ROLE_HOCVIEN;
GRANT EXECUTE ON SP_GET_ALL_COURSES TO ROLE_NHANVIEN;

-- Ensure Accountant can view invoice details (already granted in previous step, but good to double check)
-- GRANT EXECUTE ON SP_GET_INVOICE_BY_REG TO ROLE_KETOAN;
-- GRANT EXECUTE ON SP_GET_INVOICE_STUDENT_INFO TO ROLE_KETOAN;
-- GRANT EXECUTE ON SP_GET_ACCOUNTANT_REG_BY_ID TO ROLE_KETOAN;

COMMIT;
