-- Comprehensive Grant Permissions for Accountant (ROLE_KETOAN)

-- 1. Course & Class Viewing
GRANT EXECUTE ON SP_GET_ALL_COURSES TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_CLASSES TO ROLE_KETOAN;

-- 2. Registration Management
GRANT EXECUTE ON SP_GET_ACCOUNTANT_REGS TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_ACCOUNTANT_REG_BY_ID TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_REGISTRATION_BY_ID TO ROLE_KETOAN;

-- 3. Invoice Management
GRANT EXECUTE ON SP_CREATE_INVOICE TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_INVOICE_BY_REG TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_INVOICE_BY_ID TO ROLE_KETOAN;
GRANT EXECUTE ON SP_UPDATE_INVOICE_STATUS TO ROLE_KETOAN;
GRANT EXECUTE ON SP_MARK_INVOICE_PRINTED TO ROLE_KETOAN;
GRANT EXECUTE ON SP_GET_INVOICE_STUDENT_INFO TO ROLE_KETOAN;

-- 4. Payment Management (if applicable)
-- GRANT EXECUTE ON SP_CONFIRM_PAYMENT TO ROLE_KETOAN; -- If exists

COMMIT;
