-- Grant permissions for Stored Procedures
--
-- ROLE_HOCVIEN
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_MY_REGISTRATIONS TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_STUDENT_INVOICES TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_COURSES TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_COURSE_BY_ID TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_CLASSES TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_CLASS_BY_ID TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_SCHEDULE_BY_CLASS TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_REG TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_ID TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_STUDENT_INFO TO ROLE_HOCVIEN;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_INVOICE_STATUS TO ROLE_HOCVIEN; -- For requesting payment confirmation

-- ROLE_NHANVIENHOCUHOCVU
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_STUDENTS TO ROLE_NHANVIENHOCUHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_STUDENT_BY_ID TO ROLE_NHANVIENHOCUHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_SEARCH_STUDENTS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_REGISTRATIONS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_REGISTRATION_BY_ID TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_APPROVE_REGISTRATION TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_REJECT_REGISTRATION TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_FIND_STAFF_BY_SESSION TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CHECK_CLASS_SIZE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_REGISTRATION_CLASS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_CLASS_STATUS_FULL TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_STAFF_SEARCH_STUDENTS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_LOCK_ACCOUNT TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UNLOCK_ACCOUNT TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_STUDENT_REGISTRATIONS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_STUDENT_INVOICES TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_INVOICE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_REG TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_ID TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_STUDENT_INFO TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_COURSES TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_COURSE_BY_ID TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_CLASSES TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_CLASS_BY_ID TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_SCHEDULE_BY_CLASS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_SCHEDULE_BY_ID TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_CLASS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_CLASS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CHECK_CLASS_CODE_EXISTS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_COURSE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_COURSE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CHECK_COURSE_CODE_EXISTS TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_SCHEDULE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_SCHEDULE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_DELETE_SCHEDULE TO ROLE_NHANVIENHOCVU;
GRANT EXECUTE ON QLTT_ADMIN.SP_DELETE_CLASS TO ROLE_NHANVIENHOCVU;

-- ROLE_KETOAN
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_PENDING_PAYMENTS TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_PAYMENT_RECEIPT TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_CREATE_PAYMENT TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_PAYMENTS_BY_INVOICE TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_ACCOUNTANT_REGS TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_UPDATE_INVOICE_STATUS TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_ID TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_STUDENT_INFO TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_INVOICE_BY_REG TO ROLE_KETOAN;
GRANT EXECUTE ON QLTT_ADMIN.SP_GET_ACCOUNTANT_REG_BY_ID TO ROLE_KETOAN;
