-- TTTA Center Table for storing fixed public key and center info
-- Run as schema owner (e.g., QLTT_ADMIN)

-- Create TTTA table if not exists
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TTTA (
      ID_TTTA        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      TEN_TRUNG_TAM  NVARCHAR2(200) NOT NULL,
      DIA_CHI        NVARCHAR2(500),
      SO_DIEN_THOAI  VARCHAR2(20),
      KHOA_CONG_PEM  CLOB,
      CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
      UPDATED_AT     DATE
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created table TTTA');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN -- name is already used by an existing object
      DBMS_OUTPUT.PUT_LINE('Table TTTA already exists');
    ELSE
      RAISE;
    END IF;
END;
/

COMMENT ON TABLE TTTA IS 'Thông tin Trung tâm (cố định) và Public Key dùng để xác thực chữ ký số';
COMMENT ON COLUMN TTTA.TEN_TRUNG_TAM IS 'Tên Trung tâm';
COMMENT ON COLUMN TTTA.DIA_CHI IS 'Địa chỉ Trung tâm';
COMMENT ON COLUMN TTTA.SO_DIEN_THOAI IS 'Số điện thoại Trung tâm';
COMMENT ON COLUMN TTTA.KHOA_CONG_PEM IS 'Public Key RSA ở dạng PEM (cố định)';

-- Ensure one default row with ID_TTTA = 1 exists
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM TTTA;
  IF v_cnt = 0 THEN
    INSERT INTO TTTA (ID_TTTA, TEN_TRUNG_TAM, DIA_CHI, SO_DIEN_THOAI, KHOA_CONG_PEM, CREATED_AT, UPDATED_AT)
    VALUES (1, N'Trung tâm LDA', N'Lê Trọng Tấn', '0901234567', NULL, SYSDATE, SYSDATE);
    DBMS_OUTPUT.PUT_LINE('Inserted default TTTA row with ID_TTTA=1');
  END IF;
END;
/

-- Optional: create public view for reading accountant public key
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE OR REPLACE VIEW KE_TOAN_PUB AS
    SELECT kt.ID_KE_TOAN, kt.HO_TEN, kt.KHOA_CONG_PEM
    FROM KE_TOAN kt
  ]';
  DBMS_OUTPUT.PUT_LINE('Created/Updated view KE_TOAN_PUB');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Could not create view KE_TOAN_PUB: ' || SQLERRM);
END;
/

COMMIT;
