-- Script tạo sample data cho hệ thống LDA

-- 1. Tạo bảng ROLES nếu chưa có
create table qltt_admin.roles (
   role_id   number primary key,
   role_name nvarchar2(50)
);

-- 2. Tạo bảng ACCOUNTS nếu chưa có
create table qltt_admin.accounts (
   user_id  number primary key,
   username nvarchar2(50),
   password nvarchar2(255),
   email    nvarchar2(100),
   role_id  number,
   constraint fk_accounts_role foreign key ( role_id )
      references qltt_admin.roles ( role_id )
);

-- 3. Tạo bảng STUDENTS nếu chưa có
create table qltt_admin.students (
   student_id    number
      generated by default as identity
   primary key,
   full_name     nvarchar2(100),
   student_code  nvarchar2(20) unique,
   sex           nvarchar2(10),
   date_of_birth date,
   phone_number  nvarchar2(15),
   address       nvarchar2(200)
);

-- 4. Tạo bảng COURSES nếu chưa có
create table qltt_admin.courses (
   course_id    number
      generated by default as identity
   primary key,
   course_code  nvarchar2(20) unique,
   course_name  nvarchar2(100),
   description  nvarchar2(500),
   standard_fee number
);

-- 5. Tạo bảng TEACHERS nếu chưa có
create table qltt_admin.teachers (
   teacher_id   number
      generated by default as identity
   primary key,
   full_name    nvarchar2(100),
   teacher_code nvarchar2(20) unique,
   sex          nvarchar2(10),
   education    nvarchar2(100),
   phone_number nvarchar2(15)
);

-- 6. Tạo bảng CLASSES nếu chưa có
create table qltt_admin.classes (
   class_id   number
      generated by default as identity
   primary key,
   class_code nvarchar2(20) unique,
   class_name nvarchar2(100),
   start_date date,
   end_date   date,
   max_size   number,
   course_id  number,
   teacher_id number,
   constraint fk_classes_course foreign key ( course_id )
      references qltt_admin.courses ( course_id ),
   constraint fk_classes_teacher foreign key ( teacher_id )
      references qltt_admin.teachers ( teacher_id )
);

-- 7. Tạo bảng ACADEMIC_STAFF nếu chưa có
create table qltt_admin.academic_staff (
   staff_id     number
      generated by default as identity
   primary key,
   full_name    nvarchar2(100),
   staff_code   nvarchar2(20) unique,
   sex          nvarchar2(10),
   phone_number nvarchar2(15)
);

-- 8. Tạo bảng REGISTRATIONS nếu chưa có
create table qltt_admin.registrations (
   registration_id   number
      generated by default as identity
   primary key,
   registration_date date default sysdate,
   status            nvarchar2(50),
   study_date        date,
   student_id        number,
   class_id          number,
   staff_id          number,
   constraint fk_registrations_student foreign key ( student_id )
      references qltt_admin.students ( student_id ),
   constraint fk_registrations_class foreign key ( class_id )
      references qltt_admin.classes ( class_id ),
   constraint fk_registrations_staff foreign key ( staff_id )
      references qltt_admin.academic_staff ( staff_id )
);

-- 9. Tạo bảng ACCOUNTANTS nếu chưa có
create table qltt_admin.accountants (
   accountant_id number
      generated by default as identity
   primary key,
   full_name     nvarchar2(100),
   staff_code    nvarchar2(20) unique,
   sex           nvarchar2(10),
   phone_number  nvarchar2(15)
);

-- 10. Tạo bảng INVOICES nếu chưa có
create table qltt_admin.invoices (
   invoice_id      number
      generated by default as identity
   primary key,
   invoice_code    nvarchar2(20) unique,
   created_date    date default sysdate,
   due_date        date,
   amount          number,
   status          nvarchar2(50),
   registration_id number,
   constraint fk_invoices_registration foreign key ( registration_id )
      references qltt_admin.registrations ( registration_id )
);

-- 11. Tạo bảng PAYMENTS nếu chưa có
create table qltt_admin.payments (
   payment_id     number
      generated by default as identity
   primary key,
   payment_date   date default sysdate,
   amount         number,
   payment_method nvarchar2(50),
   invoice_id     number,
   accountant_id  number,
   constraint fk_payments_invoice foreign key ( invoice_id )
      references qltt_admin.invoices ( invoice_id ),
   constraint fk_payments_accountant foreign key ( accountant_id )
      references qltt_admin.accountants ( accountant_id )
);

-- 12. Tạo bảng SCHEDULES nếu chưa có
create table qltt_admin.schedules (
   schedule_id number
      generated by default as identity
   primary key,
   class_id    number,
   day_of_week number,
   start_time  timestamp,
   end_time    timestamp,
   constraint fk_schedules_class foreign key ( class_id )
      references qltt_admin.classes ( class_id )
);

-- =======================
-- SAMPLE DATA
-- =======================

-- Insert Roles
insert into qltt_admin.roles (
   role_id,
   role_name
) values ( 1,
           N'Quản trị viên' );
insert into qltt_admin.roles (
   role_id,
   role_name
) values ( 2,
           N'Nhân viên học vụ' );
insert into qltt_admin.roles (
   role_id,
   role_name
) values ( 3,
           N'Kế toán' );
insert into qltt_admin.roles (
   role_id,
   role_name
) values ( 4,
           N'Học viên' );

-- Insert Accounts
insert into qltt_admin.accounts (
   user_id,
   username,
   password,
   email,
   role_id
) values ( 1,
           'admin',
           '123456',
           'admin@lda.edu.vn',
           1 );
insert into qltt_admin.accounts (
   user_id,
   username,
   password,
   email,
   role_id
) values ( 2,
           'hocvu01',
           '123456',
           'hocvu01@lda.edu.vn',
           2 );
insert into qltt_admin.accounts (
   user_id,
   username,
   password,
   email,
   role_id
) values ( 3,
           'ketoan01',
           '123456',
           'ketoan01@lda.edu.vn',
           3 );

-- Insert Students
insert into qltt_admin.students (
   full_name,
   student_code,
   sex,
   date_of_birth,
   phone_number,
   address
) values ( N'Nguyễn Văn An',
           'HV001',
           N'Nam',
           date '1995-05-15',
           '0901234567',
           N'123 Nguyễn Trãi, Q.1, TP.HCM' );

insert into qltt_admin.students (
   full_name,
   student_code,
   sex,
   date_of_birth,
   phone_number,
   address
) values ( N'Trần Thị Bình',
           'HV002',
           N'Nữ',
           date '1997-08-20',
           '0907654321',
           N'456 Lê Lợi, Q.3, TP.HCM' );

insert into qltt_admin.students (
   full_name,
   student_code,
   sex,
   date_of_birth,
   phone_number,
   address
) values ( N'Lê Hoàng Cường',
           'HV003',
           N'Nam',
           date '1996-03-10',
           '0912345678',
           N'789 Võ Văn Tần, Q.3, TP.HCM' );

insert into qltt_admin.students (
   full_name,
   student_code,
   sex,
   date_of_birth,
   phone_number,
   address
) values ( N'Phạm Thị Duyên',
           'HV004',
           N'Nữ',
           date '1998-12-05',
           '0908765432',
           N'321 Pasteur, Q.1, TP.HCM' );

insert into qltt_admin.students (
   full_name,
   student_code,
   sex,
   date_of_birth,
   phone_number,
   address
) values ( N'Hoàng Văn Em',
           'HV005',
           N'Nam',
           date '1994-07-25',
           '0913456789',
           N'654 Cách Mạng Tháng 8, Q.10, TP.HCM' );

-- Insert Courses
insert into qltt_admin.courses (
   course_code,
   course_name,
   description,
   standard_fee
) values ( 'ENG001',
           N'English Basic',
           N'Khóa học tiếng Anh cơ bản cho người mới bắt đầu',
           2000000 );

insert into qltt_admin.courses (
   course_code,
   course_name,
   description,
   standard_fee
) values ( 'ENG002',
           N'English Intermediate',
           N'Khóa học tiếng Anh trung cấp',
           2500000 );

insert into qltt_admin.courses (
   course_code,
   course_name,
   description,
   standard_fee
) values ( 'ENG003',
           N'English Advanced',
           N'Khóa học tiếng Anh nâng cao',
           3000000 );

insert into qltt_admin.courses (
   course_code,
   course_name,
   description,
   standard_fee
) values ( 'IELTS001',
           N'IELTS Preparation',
           N'Khóa học luyện thi IELTS',
           4000000 );

insert into qltt_admin.courses (
   course_code,
   course_name,
   description,
   standard_fee
) values ( 'TOEIC001',
           N'TOEIC Preparation',
           N'Khóa học luyện thi TOEIC',
           3500000 );

-- Insert Teachers
insert into qltt_admin.teachers (
   full_name,
   teacher_code,
   sex,
   education,
   phone_number
) values ( N'John Smith',
           'GV001',
           N'Nam',
           N'Master in English Literature',
           '0909111222' );

insert into qltt_admin.teachers (
   full_name,
   teacher_code,
   sex,
   education,
   phone_number
) values ( N'Mary Johnson',
           'GV002',
           N'Nữ',
           N'Bachelor in TESOL',
           '0908333444' );

insert into qltt_admin.teachers (
   full_name,
   teacher_code,
   sex,
   education,
   phone_number
) values ( N'Nguyễn Thị Lan',
           'GV003',
           N'Nữ',
           N'Master in Applied Linguistics',
           '0907555666' );

-- Insert Academic Staff
insert into qltt_admin.academic_staff (
   full_name,
   staff_code,
   sex,
   phone_number
) values ( N'Trần Văn Học',
           'NV001',
           N'Nam',
           '0906777888' );

insert into qltt_admin.academic_staff (
   full_name,
   staff_code,
   sex,
   phone_number
) values ( N'Lê Thị Vụ',
           'NV002',
           N'Nữ',
           '0905999000' );

-- Insert Accountants
insert into qltt_admin.accountants (
   full_name,
   staff_code,
   sex,
   phone_number
) values ( N'Phạm Văn Toán',
           'KT001',
           N'Nam',
           '0904111222' );

insert into qltt_admin.accountants (
   full_name,
   staff_code,
   sex,
   phone_number
) values ( N'Võ Thị Kế',
           'KT002',
           N'Nữ',
           '0903333444' );

commit;